[SATS-544] - [FE] Integrate Update Password Functionality
abduljalilpalala/sats-project pull request #36
Opened 2022-11-13 03:28 UTC by jsvelte

2022-11-13 18:29 UTC, abduljalilpalala commented on client/src/components/molecules/AlumniSettings/index.tsx
> +            .put('/api/user/change-password', payload)
Remove await if you are going to use the `then` and `catch` after the promise is resolved.

2022-11-13 18:31 UTC, abduljalilpalala commented on client/src/hooks/auth.ts
> +        redirect('/login')
Remove `deleteCookie('XSRF-TOKEN')`, the backend will handle that one for you.
Use `window.location.href = 'login'` instead of `redirect`

2022-11-13 18:31 UTC, abduljalilpalala commented on client/src/hooks/auth.ts
> -
Remove `console.log`

2022-11-13 18:32 UTC, abduljalilpalala commented on client/src/hooks/auth.ts
>          } else {
Same with my previous comment

2022-11-13 18:32 UTC, abduljalilpalala requested changes
Please check comments.

2022-11-14 01:52 UTC, johnpaul-sun approved these changes

2022-11-14 01:52 UTC, merged